/**
 * Lightweight, curated make/model catalog used to drive the Vehicle selector.
 * Not exhaustive — enough common US-market brands and models to label an
 * estimate without free-text typing. Users can still start from a preset.
 */

export const VEHICLE_CATALOG: Record<string, string[]> = {
  Acura: ["ILX", "Integra", "TLX", "RLX", "RDX", "MDX", "NSX", "ZDX"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C"],
  Audi: [
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "TT",
    "R8",
    "e-tron",
    "Q4 e-tron",
    "e-tron GT",
  ],
  BMW: [
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "7 Series",
    "8 Series",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i3",
    "i4",
    "i5",
    "i7",
    "iX",
  ],
  Buick: [
    "Cascada",
    "Regal",
    "LaCrosse",
    "Encore",
    "Encore GX",
    "Envista",
    "Envision",
    "Enclave",
  ],
  Cadillac: [
    "ATS",
    "CTS",
    "CT4",
    "CT5",
    "CT6",
    "XTS",
    "XT4",
    "XT5",
    "XT6",
    "Escalade",
    "Lyriq",
  ],
  Chevrolet: [
    "Spark",
    "Sonic",
    "Cruze",
    "Malibu",
    "Impala",
    "Camaro",
    "Corvette",
    "Trax",
    "Trailblazer",
    "Equinox",
    "Blazer",
    "Traverse",
    "Tahoe",
    "Suburban",
    "Colorado",
    "Silverado",
    "Volt",
    "Bolt EV",
    "Bolt EUV",
    "Blazer EV",
    "Equinox EV",
    "Silverado EV",
  ],
  Chrysler: ["300", "Pacifica", "Voyager"],
  Dodge: [
    "Charger",
    "Challenger",
    "Durango",
    "Journey",
    "Grand Caravan",
    "Hornet",
  ],
  Fiat: ["500", "500L", "500X", "124 Spider"],
  Ford: [
    "Fiesta",
    "Focus",
    "Fusion",
    "Taurus",
    "Mustang",
    "EcoSport",
    "Escape",
    "Edge",
    "Flex",
    "Explorer",
    "Bronco Sport",
    "Bronco",
    "Expedition",
    "Maverick",
    "Ranger",
    "F-150",
    "Mustang Mach-E",
    "F-150 Lightning",
  ],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  GMC: [
    "Terrain",
    "Acadia",
    "Yukon",
    "Canyon",
    "Sierra",
    "Hummer EV",
  ],
  Honda: [
    "Fit",
    "Civic",
    "Insight",
    "Accord",
    "Clarity",
    "HR-V",
    "CR-V",
    "Passport",
    "Pilot",
    "Ridgeline",
    "Odyssey",
    "Prologue",
  ],
  Hyundai: [
    "Accent",
    "Elantra",
    "Sonata",
    "Veloster",
    "Venue",
    "Kona",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Santa Cruz",
    "Kona Electric",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
  ],
  Infiniti: ["Q50", "Q60", "QX30", "QX50", "QX55", "QX60", "QX80"],
  Jaguar: ["XE", "XF", "F-TYPE", "E-PACE", "F-PACE", "I-PACE"],
  Jeep: [
    "Renegade",
    "Patriot",
    "Compass",
    "Cherokee",
    "Grand Cherokee",
    "Wrangler",
    "Gladiator",
    "Wagoneer",
    "Grand Wagoneer",
  ],
  Kia: [
    "Rio",
    "Forte",
    "Optima",
    "K5",
    "Cadenza",
    "K900",
    "Stinger",
    "Soul",
    "Seltos",
    "Niro",
    "Sportage",
    "Sorento",
    "Telluride",
    "Sedona",
    "Carnival",
    "EV6",
    "EV9",
  ],
  "Land Rover": [
    "Discovery Sport",
    "Discovery",
    "Defender",
    "Range Rover Evoque",
    "Range Rover Velar",
    "Range Rover Sport",
    "Range Rover",
  ],
  Lexus: [
    "CT",
    "IS",
    "ES",
    "GS",
    "LS",
    "RC",
    "LC",
    "UX",
    "NX",
    "RX",
    "TX",
    "GX",
    "LX",
    "RZ",
  ],
  Lincoln: [
    "MKZ",
    "Continental",
    "MKC",
    "Corsair",
    "MKX",
    "Nautilus",
    "Aviator",
    "Navigator",
  ],
  Lucid: ["Air", "Gravity"],
  Maserati: ["Ghibli", "Quattroporte", "GranTurismo", "Grecale", "Levante"],
  Mazda: [
    "Mazda3",
    "Mazda6",
    "MX-5 Miata",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-9",
    "CX-70",
    "CX-90",
    "MX-30",
  ],
  "Mercedes-Benz": [
    "A-Class",
    "CLA",
    "C-Class",
    "CLS",
    "E-Class",
    "S-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "SL",
    "EQB",
    "EQE",
    "EQS",
  ],
  Mini: ["Cooper", "Clubman", "Countryman"],
  Mitsubishi: [
    "Mirage",
    "Lancer",
    "Eclipse Cross",
    "Outlander Sport",
    "Outlander",
    "Outlander PHEV",
  ],
  Nissan: [
    "Versa",
    "Sentra",
    "Altima",
    "Maxima",
    "370Z",
    "Z",
    "GT-R",
    "Juke",
    "Kicks",
    "Rogue Sport",
    "Rogue",
    "Murano",
    "Pathfinder",
    "Armada",
    "Frontier",
    "Titan",
    "Leaf",
    "Ariya",
  ],
  Polestar: ["1", "2", "3"],
  Porsche: [
    "718 Boxster",
    "718 Cayman",
    "911",
    "Panamera",
    "Macan",
    "Cayenne",
    "Taycan",
  ],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  Rivian: ["R1T", "R1S"],
  Subaru: [
    "Impreza",
    "Legacy",
    "WRX",
    "BRZ",
    "Crosstrek",
    "Forester",
    "Outback",
    "Ascent",
    "Solterra",
  ],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Toyota: [
    "Yaris",
    "Corolla",
    "Camry",
    "Avalon",
    "Crown",
    "86",
    "GR86",
    "GR Corolla",
    "GR Supra",
    "Prius",
    "Mirai",
    "C-HR",
    "Corolla Cross",
    "RAV4",
    "Venza",
    "Highlander",
    "Grand Highlander",
    "4Runner",
    "Sequoia",
    "Land Cruiser",
    "Tacoma",
    "Tundra",
    "Sienna",
    "bZ4X",
  ],
  Volkswagen: [
    "Beetle",
    "Jetta",
    "Passat",
    "Arteon",
    "Golf",
    "Taos",
    "Tiguan",
    "Atlas Cross Sport",
    "Atlas",
    "ID.4",
    "ID. Buzz",
  ],
  Volvo: [
    "S60",
    "S90",
    "V60",
    "V90",
    "XC40",
    "XC60",
    "XC90",
    "C40 Recharge",
    "EX30",
    "EX90",
  ],
};

export const VEHICLE_BRANDS = Object.keys(VEHICLE_CATALOG);

/** Model years offered in the picker: next model year down through ~30 back. */
export function vehicleYears(now = new Date().getFullYear()): number[] {
  const newest = now + 1;
  const oldest = now - 30;
  const years: number[] = [];
  for (let y = newest; y >= oldest; y--) years.push(y);
  return years;
}

/**
 * Relative depreciation factor per brand. 1.0 = the engine's baseline
 * depreciation curve (an average mainstream car). Below 1 = holds value better
 * (loses less); above 1 = depreciates faster than average. Rough,
 * resale-market-informed multipliers — not a guarantee for any single car.
 */
export const BRAND_DEPRECIATION: Record<string, number> = {
  Toyota: 0.85,
  Honda: 0.88,
  Subaru: 0.88,
  Lexus: 0.9,
  Porsche: 0.9,
  Mazda: 0.95,
  Jeep: 0.95,
  Kia: 1.0,
  Hyundai: 1.0,
  GMC: 1.0,
  Ram: 1.0,
  Acura: 1.05,
  Tesla: 1.05,
  Ford: 1.05,
  Chevrolet: 1.05,
  Dodge: 1.05,
  Mini: 1.1,
  Mitsubishi: 1.1,
  Volkswagen: 1.1,
  Nissan: 1.12,
  Buick: 1.15,
  Chrysler: 1.15,
  Genesis: 1.15,
  Volvo: 1.15,
  Cadillac: 1.2,
  Infiniti: 1.2,
  Lincoln: 1.2,
  Rivian: 1.2,
  "Land Rover": 1.25,
  BMW: 1.28,
  Audi: 1.28,
  "Mercedes-Benz": 1.3,
  Fiat: 1.3,
  Polestar: 1.3,
  "Alfa Romeo": 1.35,
  Jaguar: 1.35,
  Lucid: 1.35,
  Maserati: 1.4,
};

/**
 * Model-specific overrides for notable outliers (trucks/off-road that hold
 * value unusually well, and EVs that historically shed it fast). Keyed by
 * "Brand Model". When absent, the brand factor applies.
 */
export const MODEL_DEPRECIATION: Record<string, number> = {
  "Toyota Tacoma": 0.7,
  "Toyota 4Runner": 0.72,
  "Jeep Wrangler": 0.75,
  "Toyota Land Cruiser": 0.75,
  "Porsche 911": 0.75,
  "Toyota Tundra": 0.8,
  "Toyota RAV4": 0.8,
  "Toyota Prius": 0.82,
  "Ford F-150": 0.85,
  "Honda CR-V": 0.85,
  "Honda Ridgeline": 0.85,
  "Jeep Gladiator": 0.85,
  "Chevrolet Corvette": 0.85,
  "Chevrolet Silverado": 0.9,
  "GMC Sierra": 0.9,
  "Ford Mustang Mach-E": 1.25,
  "Hyundai Ioniq 5": 1.25,
  "Kia EV6": 1.25,
  "Audi e-tron": 1.3,
  "GMC Hummer EV": 1.3,
  "Volkswagen ID.4": 1.3,
  "Chevrolet Bolt EV": 1.35,
  "Jaguar I-PACE": 1.4,
  "Nissan Leaf": 1.4,
  "Tesla Model S": 1.15,
  "Tesla Model X": 1.15,
};

/**
 * Depreciation factor for a specific vehicle: a model override if we have one,
 * otherwise the brand factor, otherwise the neutral baseline (1.0).
 */
export function depreciationFactor(brand: string, model: string): number {
  const key = `${brand} ${model}`.trim();
  return MODEL_DEPRECIATION[key] ?? BRAND_DEPRECIATION[brand] ?? 1;
}

/** Vehicle age in years, derived from the model year (never negative). */
export function vehicleAge(year: number, now = new Date().getFullYear()): number {
  return Math.max(0, now - year);
}

/** Build the display name shown in results from the structured selections. */
export function buildVehicleName(
  year: number,
  brand: string,
  model: string
): string {
  return [year, brand, model].filter(Boolean).join(" ").trim();
}
